export type DataType = {
    _id?: string;
    name?: string;
    role?: string;
    fullName?: string;
    customerName?: string;
    emailNewletter?: string;
    emailAddress?: string;
    phoneNumber?: number;
    title?: string;
    slug?: string;
    description?: string;
    image?: string;
    imageDefault?: string;
    createdAt?: string;
    status?: string;
    rating?: number;
    price?: string;
    total?: number;
    quantityProducts?: number[];
    statusDelivery?: string;
    featureProduct?: string;
    parentCategory?: string;
 };